# Generated by Django 5.1.4 on 2026-04-15 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HREvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('contract_expiry', 'Истекает срочный договор'), ('probation_end', 'Конец испытательного срока'), ('vacation_start', 'Начало отпуска'), ('vacation_end', 'Конец отпуска'), ('birthday', 'День рождения')], max_length=30, verbose_name='Тип события')),
                ('event_date', models.DateField(verbose_name='Дата события')),
                ('notify_days_before', models.PositiveIntegerField(default=7, verbose_name='Уведомить за N дней')),
                ('notified', models.BooleanField(default=False, verbose_name='Уведомление отправлено')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата уведомления')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='companies.company', verbose_name='Компания')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='employees.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'HR-событие',
                'verbose_name_plural': 'HR-события',
                'ordering': ['event_date'],
            },
        ),
    ]
