# Generated by Django 5.1.4 on 2026-04-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companyinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='okpo',
            field=models.CharField(blank=True, max_length=10, verbose_name='ОКПО'),
        ),
    ]
