# Generated by Django 5.1.4 on 2026-04-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_okpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='okved',
            field=models.CharField(blank=True, max_length=10, verbose_name='ОКВЭД'),
        ),
        migrations.AddField(
            model_name='company',
            name='sfr_reg_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Рег. номер СФР'),
        ),
    ]
