# Generated by Django 5.1.4 on 2026-04-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_okved_company_sfr_reg_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='notify_contact',
            field=models.CharField(blank=True, help_text='Email, номер телефона или @username в Telegram', max_length=255, verbose_name='Контакт для уведомлений'),
        ),
        migrations.AddField(
            model_name='company',
            name='notify_messenger',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('viber', 'Viber')], default='email', max_length=20, verbose_name='Мессенджер для уведомлений'),
        ),
    ]
