# Generated by Django 5.1.4 on 2026-04-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_notify_contact_company_notify_messenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='notify_email_contact',
            field=models.CharField(blank=True, max_length=255, verbose_name='Email для уведомлений'),
        ),
        migrations.AddField(
            model_name='company',
            name='notify_max_contact',
            field=models.CharField(blank=True, max_length=50, verbose_name='Max номер телефона'),
        ),
        migrations.AddField(
            model_name='company',
            name='notify_telegram_contact',
            field=models.CharField(blank=True, max_length=255, verbose_name='Telegram ID (числовой)'),
        ),
        migrations.AddField(
            model_name='company',
            name='notify_viber_contact',
            field=models.CharField(blank=True, max_length=50, verbose_name='Viber номер телефона'),
        ),
        migrations.AddField(
            model_name='company',
            name='notify_whatsapp_contact',
            field=models.CharField(blank=True, max_length=50, verbose_name='WhatsApp номер телефона'),
        ),
        migrations.AlterField(
            model_name='company',
            name='notify_messenger',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('viber', 'Viber'), ('max', 'Max')], default='email', max_length=20, verbose_name='Мессенджер для уведомлений'),
        ),
    ]
