# Generated by Django 5.1.4 on 2026-04-18 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_subscription_recurring'),
        ('companies', '0004_company_okved_company_sfr_reg_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('trial', 'Пробный'), ('start', 'Старт'), ('business', 'Бизнес'), ('pro', 'Корпоратив')], default='trial', max_length=20, verbose_name='Тариф'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала'),
        ),
    ]
