# Generated by Django 5.1.4 on 2026-04-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_subscription_started_at_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='billing_period',
            field=models.CharField(choices=[('monthly', 'Помесячно'), ('annual', 'Годовой')], default='monthly', max_length=10, verbose_name='Период оплаты'),
        ),
    ]
