# Generated by Django 5.1.4 on 2026-04-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_add_billing_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='card_brand',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Тип карты'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='card_last4',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='Последние 4 цифры карты'),
        ),
    ]
