# Generated by Django 5.1.4 on 2026-04-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_add_card_last4_card_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='data_cleaned',
            field=models.BooleanField(default=False, verbose_name='Данные очищены'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='data_deletion_scheduled_at',
            field=models.DateTimeField(blank=True, help_text='Дата запланированного удаления данных компании (через 30 дней после истечения подписки)', null=True, verbose_name='Дата удаления данных'),
        ),
    ]
