# Generated by Django 5.1.4 on 2026-04-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_subscription_data_cleaned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='max_employees',
            field=models.PositiveIntegerField(default=200, verbose_name='Макс. сотрудников'),
        ),
    ]
