# Generated by Django 5.1.4 on 2026-04-15 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('hire', 'Приказ о приёме (Т-1)'), ('fire', 'Приказ об увольнении (Т-8)'), ('vacation', 'Приказ об отпуске (Т-6)'), ('transfer', 'Приказ о переводе (Т-5)'), ('salary_change', 'Изменение оклада'), ('reference', 'Справка с места работы'), ('contract', 'Трудовой договор'), ('gph_contract', 'Договор ГПХ'), ('gph_act', 'Акт выполненных работ'), ('timesheet', 'Табель (Т-13)'), ('personal_card', 'Личная карточка (Т-2)')], max_length=50, verbose_name='Тип документа')),
                ('number', models.CharField(max_length=50, verbose_name='Номер приказа')),
                ('date', models.DateField(verbose_name='Дата документа')),
                ('extra_data', models.JSONField(default=dict, verbose_name='Дополнительные данные')),
                ('pdf_file', models.FileField(blank=True, upload_to='documents/%Y/%m/', verbose_name='PDF файл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='companies.company', verbose_name='Компания')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
