# Generated by Django 5.1.4 on 2026-04-17 13:56

import apps.documents.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_okpo'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('hire', 'Приказ о приёме (Т-1)'), ('fire', 'Приказ об увольнении (Т-8)'), ('vacation', 'Приказ об отпуске (Т-6)'), ('transfer', 'Приказ о переводе (Т-5)'), ('salary_change', 'Изменение оклада'), ('reference', 'Справка с места работы'), ('contract', 'Трудовой договор'), ('gph_contract', 'Договор ГПХ'), ('gph_act', 'Акт выполненных работ'), ('dismissal', 'Приказ об увольнении'), ('bonus', 'Приказ о премии'), ('disciplinary', 'Приказ о дисциплинарном взыскании'), ('timesheet', 'Табель (Т-13)'), ('personal_card', 'Личная карточка (Т-2)')], max_length=50, verbose_name='Тип документа'),
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('hire', 'Приказ о приёме (Т-1)'), ('personal_card', 'Личная карточка (Т-2)'), ('transfer', 'Приказ о переводе (Т-5)'), ('vacation', 'Приказ об отпуске (Т-6)'), ('fire', 'Приказ об увольнении (Т-8)'), ('contract', 'Трудовой договор'), ('gph_contract', 'Договор ГПХ'), ('gph_act', 'Акт выполненных работ'), ('reference', 'Справка с места работы'), ('bonus', 'Приказ о премии'), ('disciplinary', 'Приказ о дисциплинарном взыскании'), ('salary_change', 'Изменение оклада'), ('dismissal', 'Приказ об увольнении')], max_length=50, verbose_name='Тип документа')),
                ('file', models.FileField(upload_to=apps.documents.models.template_upload_path, verbose_name='Файл шаблона')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название файла')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to='companies.company')),
            ],
            options={
                'verbose_name': 'Шаблон документа',
                'verbose_name_plural': 'Шаблоны документов',
                'unique_together': {('company', 'doc_type')},
            },
        ),
    ]
