# Generated by Django 5.1.4 on 2026-04-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_doc_type_documenttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('posted', 'Проведён')], default='draft', max_length=10, verbose_name='Статус'),
        ),
    ]
