# Generated by Django 5.1.4 on 2026-04-15 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation_type', models.CharField(choices=[('annual', 'Ежегодный оплачиваемый'), ('unpaid', 'За свой счёт'), ('maternity', 'Декретный'), ('educational', 'Учебный')], default='annual', max_length=20, verbose_name='Тип отпуска')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('days_count', models.PositiveIntegerField(default=0, verbose_name='Количество дней')),
                ('approved', models.BooleanField(default=False, verbose_name='Согласован')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document', verbose_name='Приказ')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to='employees.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Отпуск',
                'verbose_name_plural': 'Отпуска',
                'ordering': ['-start_date'],
            },
        ),
    ]
