# Generated by Django 5.1.4 on 2026-04-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0002_vacation_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacation',
            options={'ordering': ['-start_date'], 'verbose_name': 'Отпуск / заявление', 'verbose_name_plural': 'Отпуска / заявления'},
        ),
        migrations.AlterField(
            model_name='vacation',
            name='vacation_type',
            field=models.CharField(choices=[('annual', 'Ежегодный оплачиваемый'), ('unpaid', 'За свой счёт (без сохранения зарплаты)'), ('maternity', 'Декретный'), ('educational', 'Учебный')], default='annual', max_length=20, verbose_name='Тип отпуска'),
        ),
    ]
