# Generated by Django 5.1.4 on 2026-04-17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('employees', '0001_initial'),
        ('vacations', '0003_alter_vacation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_schedules', to='companies.company')),
            ],
            options={
                'verbose_name': 'График отпусков',
                'verbose_name_plural': 'Графики отпусков',
                'unique_together': {('company', 'year')},
            },
        ),
        migrations.CreateModel(
            name='VacationScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_total', models.IntegerField(default=28, verbose_name='Дней положено')),
                ('period1_start', models.DateField(blank=True, null=True, verbose_name='Период 1 начало')),
                ('period1_end', models.DateField(blank=True, null=True, verbose_name='Период 1 конец')),
                ('period2_start', models.DateField(blank=True, null=True, verbose_name='Период 2 начало')),
                ('period2_end', models.DateField(blank=True, null=True, verbose_name='Период 2 конец')),
                ('period3_start', models.DateField(blank=True, null=True, verbose_name='Период 3 начало')),
                ('period3_end', models.DateField(blank=True, null=True, verbose_name='Период 3 конец')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_schedule_entries', to='employees.employee')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='vacations.vacationschedule')),
            ],
            options={
                'verbose_name': 'Запись графика отпусков',
                'verbose_name_plural': 'Записи графика отпусков',
                'ordering': ['employee__last_name'],
            },
        ),
    ]
