# Generated by Django 5.1.4 on 2026-04-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0004_vacationschedule_vacationscheduleentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationscheduleentry',
            name='days_north',
            field=models.IntegerField(default=0, verbose_name='Северный отпуск (дней)'),
        ),
        migrations.AddField(
            model_name='vacationscheduleentry',
            name='north_start',
            field=models.DateField(blank=True, null=True, verbose_name='Северный отпуск начало'),
        ),
        migrations.AddField(
            model_name='vacationscheduleentry',
            name='north_end',
            field=models.DateField(blank=True, null=True, verbose_name='Северный отпуск конец'),
        ),
        migrations.AddField(
            model_name='vacationscheduleentry',
            name='days_extra',
            field=models.IntegerField(default=0, verbose_name='Доп. отпуск (дней)'),
        ),
        migrations.AddField(
            model_name='vacationscheduleentry',
            name='extra_start',
            field=models.DateField(blank=True, null=True, verbose_name='Доп. отпуск начало'),
        ),
        migrations.AddField(
            model_name='vacationscheduleentry',
            name='extra_end',
            field=models.DateField(blank=True, null=True, verbose_name='Доп. отпуск конец'),
        ),
    ]
