# Generated by Django 5.1.4 on 2026-04-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0006_vacationschedule_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='vacation_type',
            field=models.CharField(choices=[('annual', 'Ежегодный оплачиваемый'), ('additional', 'Дополнительный оплачиваемый'), ('unpaid', 'За свой счёт (без сохранения зарплаты)'), ('maternity', 'По беременности и родам'), ('educational', 'Учебный')], default='annual', max_length=20, verbose_name='Тип отпуска'),
        ),
    ]
