# Generated by Django 5.1.4 on 2026-04-15 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название отдела')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='companies.company')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('status', models.CharField(choices=[('active', 'Работает'), ('fired', 'Уволен'), ('on_leave', 'В отпуске'), ('on_sick', 'На больничном')], default='active', max_length=20, verbose_name='Статус')),
                ('hire_date', models.DateField(verbose_name='Дата приёма')),
                ('fire_date', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('contract_type', models.CharField(choices=[('permanent', 'Бессрочный'), ('fixed', 'Срочный'), ('gph', 'ГПХ')], default='permanent', max_length=20, verbose_name='Тип договора')),
                ('contract_end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания договора')),
                ('probation_end_date', models.DateField(blank=True, null=True, verbose_name='Конец испытательного срока')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Оклад')),
                ('personnel_number', models.CharField(blank=True, max_length=20, verbose_name='Табельный номер')),
                ('passport_series', models.CharField(blank=True, max_length=4, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(blank=True, max_length=6, verbose_name='Номер паспорта')),
                ('passport_issued_by', models.TextField(blank=True, verbose_name='Кем выдан')),
                ('passport_issued_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('passport_registration', models.TextField(blank=True, verbose_name='Адрес регистрации')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('snils', models.CharField(blank=True, max_length=14, verbose_name='СНИЛС')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='companies.company', verbose_name='Компания')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.department', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
