# Generated by Django 5.1.4 on 2026-04-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_populate_production_calendar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timerecord',
            options={'ordering': ['date'], 'verbose_name': 'Отметка табеля', 'verbose_name_plural': 'Отметки табеля'},
        ),
        migrations.AlterField(
            model_name='timerecord',
            name='code',
            field=models.CharField(choices=[('Я', 'Явка (рабочий день)'), ('ОТ', 'Отпуск ежегодный'), ('ОД', 'Отпуск доп.'), ('УЧ', 'Учебный отпуск'), ('ОЖ', 'Отпуск по беременности и родам'), ('Б', 'Больничный'), ('П', 'Праздник'), ('В', 'Выходной'), ('К', 'Командировка'), ('НН', 'Неявка невыясненная'), ('Я½', 'Неполный день'), ('РВ', 'Работа в выходной'), ('Я/С', 'Сверхурочные')], default='Я', max_length=3, verbose_name='Код'),
        ),
    ]
