# Generated by Django 5.1.4 on 2026-04-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_alter_timerecord_options_alter_timerecord_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employees/photos/', verbose_name='Фото'),
        ),
    ]
