# Generated by Django 5.1.4 on 2026-04-30 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_add_per_messenger_contacts'),
        ('employees', '0011_employee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank_account',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Расчётный счёт'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_bik',
            field=models.CharField(blank=True, default='', max_length=9, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название банка'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('main', 'Основное место работы'), ('external', 'Внешнее совместительство'), ('internal', 'Внутреннее совместительство')], default='main', max_length=10, verbose_name='Вид занятости'),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], default='', max_length=1, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='employee',
            name='residence_address',
            field=models.TextField(blank=True, default='', verbose_name='Адрес проживания'),
        ),
        migrations.CreateModel(
            name='EducationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=500, verbose_name='Учебное заведение')),
                ('specialty', models.CharField(blank=True, default='', max_length=500, verbose_name='Специальность')),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год окончания')),
                ('diploma_series', models.CharField(blank=True, default='', max_length=20, verbose_name='Серия диплома')),
                ('diploma_number', models.CharField(blank=True, default='', max_length=50, verbose_name='Номер диплома')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_records', to='employees.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образование',
                'ordering': ['-graduation_year'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('relation', models.CharField(choices=[('spouse', 'Супруг(а)'), ('child', 'Ребёнок'), ('parent', 'Родитель'), ('sibling', 'Брат/сестра'), ('other', 'Иное')], max_length=20, verbose_name='Степень родства')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='employees.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Член семьи',
                'verbose_name_plural': 'Члены семьи',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='StaffPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=255, verbose_name='Название должности')),
                ('count', models.DecimalField(decimal_places=1, default=1, max_digits=5, verbose_name='Штатных единиц')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Оклад / тарифная ставка')),
                ('bonus_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Надбавка %')),
                ('bonus_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Надбавка сумма')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примечания')),
                ('order_number', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_positions', to='companies.company', verbose_name='Компания')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.department', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Штатная единица',
                'verbose_name_plural': 'Штатное расписание',
                'ordering': ['order_number', 'position_name'],
            },
        ),
    ]
